### PR TITLE
fixed type specs in petrovich.ex

### PR DESCRIPTION
**Pull request by ppraisethesun**

### CODE REVIEW

**Comment by sobolevn** [comment]
@ppraisethesun awesome! Can you please make the CI work again?

**Comment by sobolevn** [comment]
I would love to merge this PR afterwards.

**Comment by ppraisethesun** [comment]
@sobolevn done

**Comment by sobolevn** [comment]
Awesome. Do you use this tool in production? Do you want to join the maintainers' team?

There are pretty of things to improve!

**Comment by ppraisethesun** [comment]
Yes, we use it in production and I would be glad to help

**Comment by sobolevn** [comment]
I have submitted a request to add you as a collaborator. I am not an admin myself.

**Pull request merged**
